### ISSUE TITLE
Suggestion: Permanent high score

### ISSUE THREAD

**Issue by phuang1024** [ArjunSahlot/dodger_plane#1]
The high score should be saved to a file when quitting. That ways, we can play from the same high score in another session.

**Comment by ArjunSahlot** [comment]
Good idea @HuangPatrick16777216 .

**Comment by phuang1024** [comment]
Thanks @ArjunSahlot . When should I expect the change?

**Comment by ArjunSahlot** [comment]
I have made the change @HuangPatrick16777216 . Thanks for the suggestion.
