### ISSUE TITLE
Suggestion: Pause/Start

### ISSUE THREAD

**Issue by phuang1024** [ArjunSahlot/dodger_plane#2]
The feature would pause and play the game if a key is pressed. (Remember to also check for a KEY_UP event so it will not flip between pause and play rapidly.)

**Comment by ArjunSahlot** [comment]
Thanks @HuangPatrick16777216  for a great suggestion! I will definitely work on that.

**Comment by ArjunSahlot** [comment]
I have successfully finished the feature. Thanks!
