### ISSUE TITLE
Suggestion: Gradual acceleration

### ISSUE THREAD

**Issue by phuang1024** [ArjunSahlot/dodger_plane#3]
Right now, the plane immediately accelerates to a speed when a key is pressed, and immediately stops when the key is released. I would like the plane to gradually gain speed when the key is pressed, and gradually lose speed when the key is released.

**Comment by ArjunSahlot** [comment]
I like your idea @HuangPatrick16777216, I will definitely implement it.

**Comment by ArjunSahlot** [comment]
Finished!
